# Generated by Django 4.0.5 on 2022-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_alter_details_of_book_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
